global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'olympus-app'
    kubernetes_sd_configs:
      - role: pod

    # Prometheus adds a pod name, so metrics look like
    # 'hello_requests_total_counter{instance="172.17.0.5:9102",job="olympus-app",k8s_pod="olympus-deployment-564430835-gdb24"} 42'.
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: olympus
        action: keep
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: k8s_pod
        action: replace
